
name: first work

on: push
jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: checkout repo
          uses: actions/checkout@v4
        - name: install cowsay
          uses: sudo apt-get install cowsay -y
        - name: execute cowsay
          uses: cowsay -f dragon "run for cove,hj" >> drags.txt
        - name: list
          run: ls -ltra >> drags.txt
        - name: upload arti
          uses: actions/upload-artifact@v3
          with:
             name: dragons.file
             path: drags.txt

          
