
name: first work

on: push
jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: checkout repo
          uses: actions/checkout@v4
        - name: install cowsay
          run: sudo apt-get install cowsay -y
        - name: execute cowsay
          run: cowsay -f dragon "run for cove,hj" >> drags.txt
        - name: list
          run: ls -ltra >> drags.txt
        - name: upload arti
          uses: actions/upload-artifact@v3
          with:
             name: dragons.file
             path: drags.txt

    fifrst_job:
                runs-on: ubuntu-latest
                needs: first_job
                steps:
                - name: down
                  uses: actions/download-artifact@v3
                  with: 
                    name: dragons.file
                - name: cart
                  run: 
                    |
                    ls -lhr
                    cat drags

          
